FROM node:26-alpine3.23

WORKDIR /app
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools
RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4001
CMD [ "npm", "run", "dev" ]