FROM node:26-alpine3.23

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./
RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 4001
CMD [ "npm", "run", "dev" ]